- hosts: localhost
  vars_prompt:
    - name: github_username
      prompt: Enter your GitHub Username
  vars:
    - ansible_python_interpreter: "/usr/bin/python3"
    - github_token: "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"
  tasks:
    - name: Create an Awesome GitHub Repo
      github_repo:
        github_auth_key: "{{ github_token }}"
        username: "{{ github_username }}"
        name: "{{ repo_name }}"
        description: "First repo created with custom Ansible module"
        private: yes
        has_issues: no
        has_wiki: no
        has_downloads: no
        state: present
      register: result
      tags:
        - create_repo

    - name: Delete GitHub Repo
      github_repo:
        github_auth_key:  "{{ github_token }}"
        username: "{{ github_username }}"
        name: "{{ repo_name }}"
        state: absent
      tags:
        - delete_repo
